AWS_ACCESS_KEY_ID = 'reYOURACCESSKEYHEREg'
AWS_SECRET_ACCESS_KEY = 'rePUTYOURSUPERSECRETHERETHISISANEXAMPLEr'
AWS_REGION_NAME = 'eu-west-1'
STREAM_NAME = "update-route53"
PARTITION_KEY = "shardId-000000000000"
